# --- Basics ---
set-option -g history-limit 65536
set -g -a terminal-overrides ',*:ss=\e[%p1%d q:se=\e[2 q'
set-option -g mouse on

# --- Plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark'

run '~/.tmux/plugins/tpm/tpm'
# --- Default shell ---
set-option -g default-shell /bin/zsh

# --- Clipboard & Copy-mode (for X11; use wl-copy/pbcopy if needed) ---
bind-key Enter copy-mode
setw -g mode-keys vi
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -i"
unbind -T copy-mode mousedragend1pane
unbind -T copy-mode-vi mousedragend1pane

# --- Navigation/Panes ---
set-window-option -g pane-base-index 1
set-option -s escape-time 0
bind-key c-s setw synchronize-panes
bind r source-file ~/.tmux.conf

# Switch panes using ctrl-h/j/k/l respecting Vim
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqe '^[^txz ]+ +(\\s+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"
bind -n C-\\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"

# Switch windows with ctrl-left/right
bind -n C-Left previous-window
bind -n C-Right next-window

set-option -g allow-rename off

# Pane borders
set -g pane-border-style "fg=#98971a"
set -g pane-active-border-style "fg=#98971a, bg=#323b2f"

# Status bar refinement
set-option -g status-justify "right"
set-option -g status-left-style none
set-option -g status-left-length 80
set-option -g status-right-style none
set-option -g status-right-length 80
set-window-option -g window-status-separator ""
set-window-option -g window-status-current-format "#[fg=#3c3836,bg=#fabd2f] #W #[fg=#fabd2f,bg=#3c3836]"
set-window-option -g window-status-format "#[fg=#ebdbb2,bg=#282828] #W "

# Split panes/new window in current path
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Use true color if your terminal supports it
set-option -g default-terminal "screen-256color"

# --- End of Gruvbox theme ---
set-option -g cursor-style block
set-option -g terminal-features 'xterm*:tc'
